def get_char(row, col):
    if row == 0:
        if 26 <= col <= 28: return '.'
        if 29 <= col <= 34: return ':'
        if 35 <= col <= 37: return '.'
        return ' '

    elif row == 1:
        if col == 23: return ':'
        if col == 24: return '-'
        if 25 <= col <= 26: return '+'
        if col == 27: return '*'
        if 28 <= col <= 30: return '#'
        if 31 <= col <= 35: return '*'
        if col == 36: return '+'
        if 37 <= col <= 38: return '='
        if col == 39: return '-'
        if col == 40: return ':'
        if 41 <= col <= 42: return '.'
        return ' '

    elif row == 2:
        if col == 21: return ':'
        if col == 22: return '+'
        if 23 <= col <= 25: return '#'
        if 26 <= col <= 32: return '%'
        if 33 <= col <= 38: return '#'
        if 39 <= col <= 40: return '*'
        if col == 41: return '+'
        if col == 42: return '='
        if col == 43: return ':'
        if col == 44: return '.'
        return ' '

    elif row == 3:
        if col == 20: return '-'
        if col == 21: return '#'
        if 22 <= col <= 36: return '%'
        if 37 <= col <= 40: return '#'
        if 41 <= col <= 43: return '*'
        if col == 44: return '+'
        if col == 45: return ':'
        if 46 <= col <= 47: return '.'
        return ' '

    elif row == 4:
        if col == 19: return '-'
        if col == 20: return '#'
        if 21 <= col <= 23: return '%'
        if col == 24: return '@'
        if 25 <= col <= 38: return '%'
        if 39 <= col <= 41: return '#'
        if 42 <= col <= 45: return '*'
        if col == 46: return '-'
        if col == 47: return '.'
        return ' '

    elif row == 5:
        if col == 18: return '.'
        if col == 19: return '*'
        if 20 <= col <= 21: return '%'
        if 22 <= col <= 32: return '@'
        if 33 <= col <= 39: return '%'
        if 40 <= col <= 43: return '#'
        if 44 <= col <= 46: return '*'
        if col == 47: return ':'
        return ' '

    elif row == 6:
        if col == 18: return '='
        if 19 <= col <= 21: return '%'
        if 22 <= col <= 33: return '@'
        if 34 <= col <= 40: return '%'
        if 41 <= col <= 45: return '#'
        if col == 46: return '*'
        if col == 47: return '-'
        return ' '

    elif row == 7:
        if col == 18: return '='
        if 19 <= col <= 21: return '%'
        if 22 <= col <= 34: return '@'
        if 35 <= col <= 41: return '%'
        if 42 <= col <= 45: return '#'
        if col == 46: return '*'
        if col == 47: return '='
        if col == 48: return '.'
        return ' '

    elif row == 8:
        if col == 18: return '+'
        if col == 19: return '%'
        if 20 <= col <= 33: return '@'
        if 34 <= col <= 41: return '%'
        if 42 <= col <= 45: return '#'
        if col == 46: return '*'
        if col == 47: return '='
        if col == 48: return '.'
        return ' '

    elif row == 9:
        if col == 18: return '*'
        if 19 <= col <= 20: return '%'
        if 21 <= col <= 32: return '@'
        if 33 <= col <= 41: return '%'
        if 42 <= col <= 45: return '#'
        if col == 46: return '*'
        if col == 47: return '='
        return ' '

    elif row == 10:
        if col == 17: return '.'
        if col == 18: return '#'
        if 19 <= col <= 23: return '%'
        if 24 <= col <= 31: return '@'
        if 32 <= col <= 40: return '%'
        if 41 <= col <= 45: return '#'
        if col == 46: return '*'
        if col == 47: return ':'
        return ' '

    elif row == 11:
        if col == 11: return '.'
        if 12 <= col <= 13: return ':'
        if col == 14: return '.'
        if col == 17: return ':'
        if 18 <= col <= 32: return '%'
        if 33 <= col <= 37: return '#'
        if 38 <= col <= 44: return '*'
        if col == 45: return '#'
        if col == 46: return '*'
        if col == 47: return ':'
        return ' '

    elif row == 12:
        if col == 11: return '-'
        if col == 12: return '*'
        if 13 <= col <= 14: return '%'
        if col == 15: return '#'
        if col == 16: return '*'
        if col == 17: return '#'
        if 18 <= col <= 32: return '%'
        if 33 <= col <= 35: return '#'
        if 36 <= col <= 46: return '*'
        if col == 47: return ':'
        return ' '

    elif row == 13:
        if col == 13: return '.'
        if col == 14: return ':'
        if col == 15: return '*'
        if 16 <= col <= 22: return '@'
        if 23 <= col <= 31: return '%'
        if 32 <= col <= 35: return '#'
        if 36 <= col <= 41: return '*'
        if 42 <= col <= 46: return '+'
        if col == 47: return '-'
        return ' '

    elif row == 14:
        if col == 13: return '.'
        if col == 14: return '+'
        if 15 <= col <= 18: return '@'
        if col == 19: return '#'
        if 20 <= col <= 21: return '*'
        if 22 <= col <= 26: return '#'
        if 27 <= col <= 31: return '*'
        if 32 <= col <= 37: return '#'
        if 38 <= col <= 41: return '*'
        if 42 <= col <= 45: return '#'
        if 46 <= col <= 48: return '*'
        if 49 <= col <= 50: return '+'
        if col == 51: return '='
        if col == 52: return ':'
        return ' '

    elif row == 15:
        if col == 13: return '*'
        if 14 <= col <= 16: return '@'
        if col == 17: return '%'
        if col == 18: return '#'
        if col == 19: return '+'
        if 20 <= col <= 23: return '='
        if 24 <= col <= 25: return '+'
        if 26 <= col <= 33: return '='
        if 34 <= col <= 41: return '-'
        if col == 42: return '*'
        if 43 <= col <= 46: return '@'
        if col == 47: return '%'
        if col == 48: return '*'
        if col == 49: return ':'
        if 50 <= col <= 51: return '.'
        return ' '

    elif row == 16:
        if col == 13: return '*'
        if 14 <= col <= 15: return '@'
        if 16 <= col <= 17: return '%'
        if col == 18: return '*'
        if 19 <= col <= 21: return '='
        if 22 <= col <= 24: return '*'
        if col == 25: return '+'
        if col == 26: return '='
        if 27 <= col <= 31: return '-'
        if 32 <= col <= 35: return ':'
        if 36 <= col <= 41: return '.'
        if col == 42: return '-'
        if col == 43: return '#'
        if col == 44: return '@'
        if 45 <= col <= 46: return '%'
        if col == 47: return '#'
        if col == 48: return '+'
        return ' '

    elif row == 17:
        if col == 14: return '*'
        if col == 15: return '@'
        if col == 16: return '%'
        if col == 17: return '#'
        if 18 <= col <= 19: return '='
        if col == 20: return '*'
        if 21 <= col <= 25: return '%'
        if col == 26: return '*'
        if col == 27: return '-'
        if 28 <= col <= 32: return ':'
        if 33 <= col <= 36: return '-'
        if col == 37: return ':'
        if col == 38: return '.'
        if col == 40: return '.'
        if col == 42: return ':'
        if col == 43: return '*'
        if 44 <= col <= 45: return '%'
        if col == 46: return '#'
        if col == 47: return '-'
        if col == 48: return '.'
        return ' '

    elif row == 18:
        if col == 15: return '+'
        if col == 16: return '@'
        if col == 17: return '+'
        if col == 18: return '-'
        if 19 <= col <= 20: return '+'
        if col == 21: return '='
        if 22 <= col <= 24: return '+'
        if 25 <= col <= 26: return '='
        if col == 27: return '-'
        if 28 <= col <= 31: return ':'
        if col == 32: return '-'
        if col == 33: return '='
        if col == 34: return '+'
        if col == 35: return '*'
        if col == 36: return '#'
        if 37 <= col <= 38: return '*'
        if col == 39: return '-'
        if col == 40: return '.'
        if col == 42: return '.'
        if col == 43: return '='
        if col == 44: return '#'
        if col == 45: return '%'
        if col == 46: return '+'
        return ' '

    elif row == 19:
        if col == 15: return ':'
        if col == 16: return '%'
        if col == 17: return '='
        if col == 18: return '-'
        if col == 19: return '='
        if col == 20: return '*'
        if 21 <= col <= 24: return '%'
        if col == 25: return '#'
        if col == 26: return '*'
        if col == 27: return '+'
        if col == 28: return '-'
        if col == 29: return ':'
        if 30 <= col <= 31: return '.'
        if col == 32: return ':'
        if col == 33: return '-'
        if 34 <= col <= 36: return '+'
        if col == 37: return '='
        if col == 38: return ':'
        if col == 39: return '='
        if col == 40: return '-'
        if col == 43: return '-'
        if col == 44: return '#'
        if col == 45: return '%'
        if col == 46: return '='
        return ' '

    elif row == 20:
        if col == 15: return '='
        if col == 16: return '*'
        if col == 17: return '-'
        if col == 18: return ':'
        if col == 19: return '-'
        if col == 20: return '+'
        if 21 <= col <= 23: return '#'
        if col == 24: return '*'
        if col == 25: return '%'
        if col == 26: return '#'
        if col == 27: return '='
        if col == 28: return ':'
        if col == 29: return '.'
        if col == 31: return '.'
        if col == 32: return '-'
        if col == 33: return '#'
        if col == 34: return '*'
        if col == 35: return '#'
        if 36 <= col <= 37: return '+'
        if col == 38: return '='
        if 39 <= col <= 40: return '.'
        if col == 43: return '='
        if col == 44: return '*'
        if col == 45: return '-'
        return ' '

    elif row == 21:
        if col == 15: return '-'
        if col == 16: return '#'
        if col == 17: return '-'
        if 18 <= col <= 20: return ':'
        if col == 21: return '-'
        if col == 22: return '='
        if 23 <= col <= 24: return '+'
        if col == 25: return '='
        if 26 <= col <= 27: return '-'
        if col == 28: return ':'
        if col == 29: return '.'
        if col == 32: return ':'
        if 33 <= col <= 35: return '+'
        if col == 36: return '-'
        if 37 <= col <= 38: return ':'
        if col == 39: return '.'
        if col == 43: return ':'
        if col == 44: return '.'
        if col == 45: return ':'
        return ' '

    elif row == 22:
        if col == 15: return ':'
        if col == 16: return '+'
        if 17 <= col <= 18: return '-'
        if 19 <= col <= 25: return ':'
        if col == 26: return '-'
        if col == 27: return ':'
        if col == 28: return '.'
        if 33 <= col <= 36: return '.'
        if 43 <= col <= 44: return '-'
        if col == 45: return '.'
        return ' '

    elif row == 23:
        if 16 <= col <= 17: return '='
        if 18 <= col <= 20: return '-'
        if 21 <= col <= 23: return ':'
        if 24 <= col <= 25: return '-'
        if 26 <= col <= 27: return ':'
        if col == 28: return '.'
        if 34 <= col <= 39: return '.'
        if 43 <= col <= 44: return ':'
        return ' '

    elif row == 24:
        if col == 16: return '.'
        if 17 <= col <= 21: return '-'
        if 22 <= col <= 24: return ':'
        if col == 25: return '-'
        if col == 26: return '+'
        if col == 27: return '='
        if col == 28: return '.'
        if col == 30: return ':'
        if col == 31: return '.'
        if 33 <= col <= 39: return '.'
        if 42 <= col <= 43: return '.'
        return ' '

    elif row == 25:
        if col == 17: return '.'
        if 18 <= col <= 20: return '-'
        if 21 <= col <= 23: return ':'
        if col == 24: return '='
        if col == 25: return '%'
        if col == 26: return '@'
        if col == 27: return '%'
        if col == 28: return '#'
        if col == 29: return '*'
        if col == 30: return '%'
        if col == 31: return '*'
        if 36 <= col <= 37: return '.'
        if 41 <= col <= 42: return '.'
        return ' '

    elif row == 26:
        if col == 18: return ':'
        if 19 <= col <= 20: return '-'
        if col == 21: return ':'
        if col == 22: return '-'
        if col == 23: return ':'
        if col == 24: return '#'
        if 25 <= col <= 28: return '@'
        if 29 <= col <= 30: return '%'
        if col == 31: return '@'
        if col == 32: return '='
        return ' '

    elif row == 27:
        if col == 18: return '.'
        if col == 19: return '='
        if 20 <= col <= 22: return '-'
        if col == 23: return '='
        if 24 <= col <= 25: return '+'
        if 26 <= col <= 27: return '*'
        if col == 28: return '+'
        if 29 <= col <= 31: return '='
        if col == 32: return ':'
        return ' '

    elif row == 28:
        if col == 18: return '.'
        if 19 <= col <= 21: return '='
        if 22 <= col <= 27: return '-'
        if col == 28: return ':'
        if 29 <= col <= 34: return '.'
        if col == 39: return '.'
        return ' '

    elif row == 29:
        if col == 18: return ':'
        if col == 19: return '='
        if col == 20: return '+'
        if col == 21: return '='
        if 22 <= col <= 26: return '-'
        if 27 <= col <= 28: return ':'
        if 29 <= col <= 31: return '.'
        if col == 37: return '.'
        if col == 38: return ':'
        if col == 39: return '.'
        return ' '

    elif row == 30:
        if col == 16: return '-'
        if col == 17: return '*'
        if 18 <= col <= 19: return ':'
        if col == 20: return '-'
        if 21 <= col <= 22: return '='
        if col == 23: return '-'
        if 24 <= col <= 26: return ':'
        if 27 <= col <= 30: return '.'
        if col == 35: return '.'
        if 36 <= col <= 37: return ':'
        if col == 39: return '.'
        if col == 40: return '*'
        if col == 41: return '='
        if col == 42: return '.'
        return ' '

    elif row == 31:
        if col == 14: return '.'
        if col == 15: return '='
        if col == 16: return '#'
        if col == 17: return '%'
        if col == 18: return '*'
        if 19 <= col <= 20: return ':'
        if col == 21: return '.'
        if col == 22: return '-'
        if 23 <= col <= 24: return '='
        if col == 25: return '-'
        if 26 <= col <= 28: return ':'
        if 29 <= col <= 32: return '.'
        if col == 33: return ':'
        if col == 34: return '-'
        if 35 <= col <= 36: return '.'
        if col == 39: return '.'
        if col == 40: return '*'
        if col == 41: return '%'
        if col == 42: return '+'
        if col == 43: return '-'
        if col == 44: return '.'
        return ' '

    elif row == 32:
        if col == 13: return '-'
        if col == 14: return '*'
        if 15 <= col <= 16: return '#'
        if 17 <= col <= 18: return '%'
        if col == 19: return '#'
        if col == 20: return '+'
        if col == 21: return '-'
        if 22 <= col <= 24: return ':'
        if 25 <= col <= 30: return '-'
        if col == 31: return '='
        if col == 32: return '*'
        if col == 33: return '='
        if col == 34: return '.'
        if col == 38: return ':'
        if col == 39: return '-'
        if col == 40: return '='
        if col == 41: return '%'
        if col == 42: return '*'
        if col == 43: return '+'
        if col == 44: return '='
        if col == 45: return '-'
        if col == 46: return '.'
        return ' '

    elif row == 33:
        if col == 11: return '.'
        if col == 12: return '+'
        if 13 <= col <= 14: return '%'
        if 15 <= col <= 16: return '#'
        if 17 <= col <= 18: return '%'
        if col == 19: return '#'
        if 20 <= col <= 21: return '%'
        if col == 22: return '#'
        if col == 23: return '*'
        if col == 24: return '='
        if 25 <= col <= 26: return ':'
        if 27 <= col <= 29: return '-'
        if 30 <= col <= 31: return '+'
        if col == 32: return ':'
        if col == 35: return '.'
        if col == 36: return ':'
        if col == 37: return '-'
        if col == 38: return '='
        if col == 39: return '-'
        if col == 40: return '+'
        if col == 41: return '%'
        if 42 <= col <= 43: return '*'
        if 44 <= col <= 45: return '+'
        if col == 46: return '='
        if col == 47: return ':'
        if col == 48: return '.'
        return ' '

    elif row == 34:
        if col == 9: return ':'
        if col == 10: return '='
        if col == 11: return '#'
        if 12 <= col <= 15: return '%'
        if 16 <= col <= 17: return '#'
        if 18 <= col <= 19: return '%'
        if 20 <= col <= 21: return '#'
        if 22 <= col <= 25: return '%'
        if col == 26: return '+'
        if col == 27: return '-'
        if col == 28: return ':'
        if 29 <= col <= 30: return '-'
        if col == 31: return '.'
        if col == 33: return '.'
        if col == 34: return ':'
        if 35 <= col <= 37: return '='
        if 38 <= col <= 39: return '-'
        if col == 40: return '*'
        if col == 41: return '#'
        if 42 <= col <= 44: return '*'
        if 45 <= col <= 47: return '+'
        if 48 <= col <= 49: return '='
        if col == 50: return '-'
        if col == 51: return '.'
        return ' '

    elif row == 35:
        if col == 4: return '.'
        if col == 5: return ':'
        if col == 6: return '-'
        if col == 7: return '+'
        if col == 8: return '*'
        if col == 9: return '#'
        if 10 <= col <= 12: return '%'
        if 13 <= col <= 14: return '#'
        if col == 15: return '%'
        if 16 <= col <= 18: return '#'
        if 19 <= col <= 20: return '%'
        if col == 21: return '#'
        if col == 22: return '*'
        if col == 23: return '#'
        if 24 <= col <= 26: return '%'
        if col == 27: return '#'
        if col == 28: return '*'
        if col == 29: return '+'
        if 30 <= col <= 31: return '='
        if col == 32: return ':'
        if col == 33: return '-'
        if col == 34: return '='
        if 35 <= col <= 37: return '+'
        if col == 38: return '-'
        if col == 39: return '+'
        if 40 <= col <= 47: return '*'
        if 48 <= col <= 51: return '+'
        if col == 52: return '='
        if col == 53: return '-'
        if 54 <= col <= 55: return ':'
        if col == 56: return '.'
        return ' '

    elif row == 36:
        if col == 0: return '.'
        if col == 1: return ':'
        if col == 2: return '='
        if col == 3: return '+'
        if 4 <= col <= 5: return '#'
        if 6 <= col <= 7: return '%'
        if 8 <= col <= 9: return '#'
        if 10 <= col <= 14: return '%'
        if 15 <= col <= 18: return '#'
        if 19 <= col <= 20: return '*'
        if col == 21: return '#'
        if col == 22: return '%'
        if col == 23: return '#'
        if col == 24: return '*'
        if 25 <= col <= 26: return '#'
        if 27 <= col <= 28: return '%'
        if col == 29: return '#'
        if col == 30: return '+'
        if 31 <= col <= 32: return '='
        if col == 33: return '-'
        if col == 34: return '='
        if col == 35: return '-'
        if col == 36: return '+'
        if col == 37: return '-'
        if col == 38: return '='
        if 39 <= col <= 45: return '*'
        if col == 46: return '#'
        if 47 <= col <= 48: return '%'
        if col == 49: return '*'
        if 50 <= col <= 56: return '+'
        if col == 57: return '='
        if col == 58: return ':'
        if col == 59: return '.'
        return ' '

    elif row == 37:
        if col == 0: return '*'
        if 1 <= col <= 3: return '#'
        if 4 <= col <= 7: return '%'
        if 8 <= col <= 9: return '#'
        if 10 <= col <= 13: return '%'
        if 14 <= col <= 15: return '#'
        if 16 <= col <= 22: return '*'
        if 23 <= col <= 24: return '#'
        if col == 25: return '*'
        if col == 26: return '+'
        if col == 27: return '*'
        if col == 28: return '#'
        if col == 29: return '%'
        if col == 30: return '*'
        if col == 31: return '+'
        if 32 <= col <= 33: return '='
        if col == 34: return ':'
        if col == 35: return '.'
        if col == 36: return ':'
        if col == 37: return '-'
        if col == 38: return '*'
        if col == 39: return '#'
        if 40 <= col <= 49: return '*'
        if 50 <= col <= 53: return '+'
        if 54 <= col <= 57: return '*'
        if col == 58: return '+'
        if col == 59: return '='
        return ' '

    elif row == 38:
        if 0 <= col <= 9: return '#'
        if 10 <= col <= 11: return '%'
        if col == 12: return '#'
        if 13 <= col <= 14: return '%'
        if 15 <= col <= 17: return '#'
        if 18 <= col <= 22: return '*'
        if col == 23: return '+'
        if 24 <= col <= 25: return '*'
        if 26 <= col <= 27: return '+'
        if col == 28: return '='
        if col == 29: return '#'
        if col == 30: return '%'
        if col == 31: return '*'
        if col == 32: return '+'
        if col == 33: return '#'
        if col == 34: return '+'
        if 35 <= col <= 36: return ':'
        if col == 37: return '='
        if col == 38: return '#'
        if 39 <= col <= 46: return '*'
        if 47 <= col <= 48: return '+'
        if col == 49: return '*'
        if 50 <= col <= 52: return '+'
        if 53 <= col <= 57: return '*'
        if 58 <= col <= 59: return '+'
        return ' '

    elif row == 39:
        if 0 <= col <= 6: return '#'
        if 7 <= col <= 12: return '%'
        if 13 <= col <= 15: return '@'
        if col == 16: return '%'
        if 17 <= col <= 18: return '#'
        if 19 <= col <= 23: return '*'
        if 24 <= col <= 25: return '+'
        if 26 <= col <= 27: return '='
        if col == 28: return '-'
        if col == 29: return '='
        if 30 <= col <= 31: return '*'
        if 32 <= col <= 33: return '+'
        if col == 34: return '='
        if col == 35: return ':'
        if col == 36: return '-'
        if col == 37: return '+'
        if 38 <= col <= 49: return '*'
        if 50 <= col <= 53: return '+'
        if 54 <= col <= 57: return '*'
        if 58 <= col <= 59: return '+'
        return ' '

    elif row == 40:
        if 0 <= col <= 8: return '#'
        if 9 <= col <= 15: return '%'
        if 16 <= col <= 18: return '@'
        if col == 19: return '%'
        if col == 20: return '#'
        if 21 <= col <= 24: return '*'
        if col == 25: return '+'
        if 26 <= col <= 27: return '='
        if 28 <= col <= 30: return '-'
        if col == 31: return '+'
        if 32 <= col <= 33: return '*'
        if col == 34: return '='
        if col == 35: return '-'
        if col == 36: return '+'
        if 37 <= col <= 49: return '*'
        if 50 <= col <= 54: return '+'
        if 55 <= col <= 56: return '*'
        if 57 <= col <= 58: return '+'
        if col == 59: return '*'
        return ' '

    elif row == 41:
        if 0 <= col <= 9: return '#'
        if col == 10: return '%'
        if 11 <= col <= 16: return '#'
        if 17 <= col <= 18: return '%'
        if 19 <= col <= 20: return '@'
        if col == 21: return '%'
        if col == 22: return '#'
        if 23 <= col <= 25: return '*'
        if 26 <= col <= 27: return '+'
        if col == 28: return '='
        if col == 29: return '-'
        if col == 30: return ':'
        if col == 31: return '-'
        if col == 32: return '+'
        if col == 33: return '*'
        if col == 34: return '-'
        if col == 35: return '='
        if col == 36: return '+'
        if 37 <= col <= 44: return '*'
        if 45 <= col <= 46: return '#'
        if 47 <= col <= 50: return '*'
        if 51 <= col <= 53: return '+'
        if 54 <= col <= 57: return '*'
        if col == 58: return '+'
        if col == 59: return '#'
        return ' '

    elif row == 42:
        if 0 <= col <= 19: return '#'
        if col == 20: return '%'
        if 21 <= col <= 22: return '@'
        if col == 23: return '%'
        if col == 24: return '#'
        if 25 <= col <= 26: return '*'
        if 27 <= col <= 28: return '+'
        if 29 <= col <= 31: return '-'
        if 32 <= col <= 34: return '='
        if col == 35: return '+'
        if col == 36: return '*'
        if col == 37: return '#'
        if 38 <= col <= 42: return '*'
        if 43 <= col <= 45: return '#'
        if 46 <= col <= 51: return '*'
        if 52 <= col <= 53: return '+'
        if 54 <= col <= 58: return '*'
        if col == 59: return '#'
        return ' '

    elif row == 43:
        if 0 <= col <= 1: return '%'
        if 2 <= col <= 21: return '#'
        if col == 22: return '%'
        if 23 <= col <= 24: return '@'
        if col == 25: return '%'
        if col == 26: return '*'
        if col == 27: return '+'
        if col == 28: return '*'
        if 29 <= col <= 31: return '='
        if col == 32: return '+'
        if col == 33: return '='
        if col == 34: return '+'
        if col == 35: return '*'
        if 36 <= col <= 37: return '#'
        if 38 <= col <= 40: return '*'
        if col == 41: return '#'
        if 42 <= col <= 47: return '*'
        if 48 <= col <= 53: return '+'
        if 54 <= col <= 59: return '*'
        return ' '

    return ' '

def render():
    for r in range(44):
        line = ''
        for c in range(60):
            line += get_char(r, c)
        print(line)

if __name__ == '__main__':
    render()
